[package]
name = "chip8"
version = "0.1.0"
edition = "2021"


[dependencies]
chip8_core = { path = "../chip8-core" }
pixels = "0.15.0"
log = "0.4"
simplelog = "0.12"
winit = "0.30.8"
winit_input_helper = "0.15"
